### ISSUE TITLE
deploy on github pages

### ISSUE THREAD

**Issue by AlexanderARodin** [tuzz/minimal-rust-wasm#1]
https://github.com/tuzz/minimal-rust-wasm/blob/ae74acbd666aad8a9a86c3542c4dc553d8597c79/bin/deploy#L18C1-L19C1

Linked line above has some limitations and not obvious requirements.
More straight forward and simple way is using **`.github/workflows/`** for deploy parts directly from prepared directory (for instance **tmp**). For example, you can find little example below:
```yaml
# steps for preparing, cloning, compiling etc
#  ...
#  - name: Build
#    run: |
#      /bin/wasm_release
#      rm -rf tmp
#      mkdir -p tmp/target
#      cd tmp
#      cp ../index.html .
#      cp ../target/index.wasm target
#      cp ../target/index.js target
# ...

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: tmp
        single-commit: true
```

Sincerely,
A.
